name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black

      - name: Lint with black
        run: |
          black . --check

      - name: Test with pytest
        run: |
          python -m pytest

      - name: Smoke test with cost guardrails
        run: |
          echo "Running smoke test with ≤10 shots limit..."
          python tests/test_smoke_braket.py
        env:
          # Ensure we're in CI mode for cost safety
          CI: true
